;;; tibetan-verb-classifier.el --- Tibetan verb classification (Hill 2010) -*- lexical-binding: t -*-

;;; Commentary:
;; Provides verb lookup and classification based on Nathan Hill's
;; "A Lexicon of Tibetan Verb Stems as Reported by the Grammatical Tradition" (2010).
;;
;; Features:
;; - Verb stem recognition (present, past, future, imperative)
;; - Transitivity classification (transitive/intransitive)
;; - Volitionality classification (volitional/non-volitional)
;; - Case frame analysis (ERG-ABS, ABS, etc.)
;; - Indigenous class (tha dad pa / tha mi dad pa)

;;; Code:

(require 'cl-lib)

;; ============================================================================
;; VERB DATABASE
;; Based on Hill 2010 and common classical Tibetan verbs
;; Format: (lemma . properties-alist)
;; ============================================================================

(defvar tibetan-verb-database nil
  "Hash table of Tibetan verbs with grammatical information.")

(defun tibetan-verb-database--initialize ()
  "Initialize the verb database. Always rebuilds from scratch."
  (let ((db (make-hash-table :test 'equal)))
    ;; Common verbs with full Hill 2010 style entries
    ;; Format: present / past / future / imperative

    ;; བྱེད་ - to do/make (transitive)
    (puthash "བྱེད" '((lemma . "བྱེད")
                     (meaning . "to do, to make")
                     (present_stem . "བྱེད")
                     (past_stem . "བྱས")
                     (future_stem . "བྱ")
                     (imperative_stem . "བྱོས")
                     (transitivity . "Transitive")
                     (volitionality . "Volitional")
                     (case_frame . "Erg-Abs")
                     (indigenous_class . "tha_dad_pa")) db)
    (puthash "བྱས" (gethash "བྱེད" db) db)
    (puthash "བྱ" (gethash "བྱེད" db) db)
    (puthash "བྱོས" (gethash "བྱེད" db) db)

    ;; གསུང་ - to speak (honorific, transitive)
    (puthash "གསུང" '((lemma . "གསུང")
                      (meaning . "to speak, to say (hon.)")
                      (present_stem . "གསུང")
                      (past_stem . "གསུངས")
                      (future_stem . "གསུང")
                      (imperative_stem . "གསུངས")
                      (transitivity . "Transitive")
                      (volitionality . "Volitional")
                      (case_frame . "Erg-Abs")
                      (indigenous_class . "tha_dad_pa")) db)
    (puthash "གསུངས" (gethash "གསུང" db) db)

    ;; སྨྲ་ - to speak (ordinary)
    (puthash "སྨྲ" '((lemma . "སྨྲ")
                    (meaning . "to speak, to say")
                    (present_stem . "སྨྲ")
                    (past_stem . "སྨྲས")
                    (future_stem . "སྨྲ")
                    (imperative_stem . "སྨྲོས")
                    (transitivity . "Transitive")
                    (volitionality . "Volitional")
                    (case_frame . "Erg-Abs")
                    (indigenous_class . "tha_dad_pa")) db)
    (puthash "སྨྲས" (gethash "སྨྲ" db) db)

    ;; འགྲོ་ - to go (intransitive)
    (puthash "འགྲོ" '((lemma . "འགྲོ")
                      (meaning . "to go")
                      (present_stem . "འགྲོ")
                      (past_stem . "སོང")
                      (future_stem . "འགྲོ")
                      (imperative_stem . "སོང")
                      (transitivity . "Intransitive")
                      (volitionality . "Volitional")
                      (case_frame . "Abs")
                      (indigenous_class . "tha_mi_dad_pa")) db)
    (puthash "སོང" (gethash "འགྲོ" db) db)

    ;; འོང་ - to come (intransitive)
    (puthash "འོང" '((lemma . "འོང")
                     (meaning . "to come")
                     (present_stem . "འོང")
                     (past_stem . "འོངས")
                     (future_stem . "འོང")
                     (imperative_stem . "ཤོག")
                     (transitivity . "Intransitive")
                     (volitionality . "Volitional")
                     (case_frame . "Abs")
                     (indigenous_class . "tha_mi_dad_pa")) db)
    (puthash "འོངས" (gethash "འོང" db) db)
    (puthash "ཤོག" (gethash "འོང" db) db)

    ;; བཞུགས་ - to stay/reside (hon., intransitive)
    (puthash "བཞུགས" '((lemma . "བཞུགས")
                        (meaning . "to stay, to reside (hon.)")
                        (present_stem . "བཞུགས")
                        (past_stem . "བཞུགས")
                        (future_stem . "བཞུགས")
                        (imperative_stem . "བཞུགས")
                        (transitivity . "Intransitive")
                        (volitionality . "Volitional")
                        (case_frame . "Abs-Loc")
                        (indigenous_class . "tha_mi_dad_pa")) db)

    ;; མཐོང་ - to see (transitive)
    (puthash "མཐོང" '((lemma . "མཐོང")
                       (meaning . "to see")
                       (present_stem . "མཐོང")
                       (past_stem . "མཐོང")
                       (future_stem . "མཐོང")
                       (imperative_stem . "མཐོངས")
                       (transitivity . "Transitive")
                       (volitionality . "Non-volitional")
                       (case_frame . "Erg-Abs")
                       (indigenous_class . "tha_dad_pa")) db)

    ;; གཟིགས་ - to see (hon.)
    (puthash "གཟིགས" '((lemma . "གཟིགས")
                        (meaning . "to see, to look (hon.)")
                        (present_stem . "གཟིགས")
                        (past_stem . "གཟིགས")
                        (future_stem . "གཟིགས")
                        (imperative_stem . "གཟིགས")
                        (transitivity . "Transitive")
                        (volitionality . "Volitional")
                        (case_frame . "Erg-Abs")
                        (indigenous_class . "tha_dad_pa")) db)

    ;; ཐོས་ - to hear (transitive)
    (puthash "ཐོས" '((lemma . "ཐོས")
                     (meaning . "to hear")
                     (present_stem . "ཐོས")
                     (past_stem . "ཐོས")
                     (future_stem . "ཐོས")
                     (imperative_stem . "ཐོས")
                     (transitivity . "Transitive")
                     (volitionality . "Non-volitional")
                     (case_frame . "Erg-Abs")
                     (indigenous_class . "tha_dad_pa")) db)

    ;; མཁྱེན་ - to know (hon.)
    (puthash "མཁྱེན" '((lemma . "མཁྱེན")
                        (meaning . "to know (hon.)")
                        (present_stem . "མཁྱེན")
                        (past_stem . "མཁྱེན")
                        (future_stem . "མཁྱེན")
                        (imperative_stem . "མཁྱེན")
                        (transitivity . "Transitive")
                        (volitionality . "Volitional")
                        (case_frame . "Erg-Abs")
                        (indigenous_class . "tha_dad_pa")) db)

    ;; ཤེས་ - to know (transitive)
    (puthash "ཤེས" '((lemma . "ཤེས")
                     (meaning . "to know, to understand")
                     (present_stem . "ཤེས")
                     (past_stem . "ཤེས")
                     (future_stem . "ཤེས")
                     (imperative_stem . "ཤེས")
                     (transitivity . "Transitive")
                     (volitionality . "Non-volitional")
                     (case_frame . "Erg-Abs")
                     (indigenous_class . "tha_dad_pa")) db)

    ;; བྱིན་ - to give (transitive)
    (puthash "བྱིན" '((lemma . "སྦྱིན")
                      (meaning . "to give")
                      (present_stem . "སྦྱིན")
                      (past_stem . "བྱིན")
                      (future_stem . "སྦྱིན")
                      (imperative_stem . "སྦྱིན")
                      (transitivity . "Transitive")
                      (volitionality . "Volitional")
                      (case_frame . "Erg-Abs-Dat")
                      (indigenous_class . "tha_dad_pa")) db)
    (puthash "སྦྱིན" (gethash "བྱིན" db) db)

    ;; བཅུག་ - to put in, to cause (transitive causative)
    (puthash "བཅུག" '((lemma . "འཇུག")
                       (meaning . "to put in, to cause, to insert")
                       (present_stem . "འཇུག")
                       (past_stem . "བཅུག")
                       (future_stem . "གཞུག")
                       (imperative_stem . "ཆུག")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs-Loc")
                       (indigenous_class . "tha_dad_pa")) db)
    (puthash "འཇུག" (gethash "བཅུག" db) db)
    (puthash "གཞུག" (gethash "བཅུག" db) db)
    (puthash "ཆུག" (gethash "བཅུག" db) db)

    ;; བརྗོད་ - to recite, to express (transitive)
    (puthash "བརྗོད" '((lemma . "བརྗོད")
                        (meaning . "to recite, to express, to utter")
                        (present_stem . "བརྗོད")
                        (past_stem . "བརྗོད")
                        (future_stem . "བརྗོད")
                        (imperative_stem . "བརྗོད")
                        (transitivity . "Transitive")
                        (volitionality . "Volitional")
                        (case_frame . "Erg-Abs")
                        (indigenous_class . "tha_dad_pa")) db)

    ;; ཉན་ - to listen (transitive)
    (puthash "ཉན" '((lemma . "ཉན")
                    (meaning . "to listen, to hear")
                    (present_stem . "ཉན")
                    (past_stem . "ཉན")
                    (future_stem . "ཉན")
                    (imperative_stem . "ཉོན")
                    (transitivity . "Transitive")
                    (volitionality . "Volitional")
                    (case_frame . "Erg-Abs")
                    (indigenous_class . "tha_dad_pa")) db)
    (puthash "ཉོན" (gethash "ཉན" db) db)

    ;; ཐོབ་ - to obtain (transitive)
    (puthash "ཐོབ" '((lemma . "ཐོབ")
                     (meaning . "to obtain, to get, to receive")
                     (present_stem . "ཐོབ")
                     (past_stem . "ཐོབ")
                     (future_stem . "ཐོབ")
                     (imperative_stem . "ཐོབས")
                     (transitivity . "Transitive")
                     (volitionality . "Non-volitional")
                     (case_frame . "Erg-Abs")
                     (indigenous_class . "tha_dad_pa")) db)

    ;; སྐྱེ་ - to be born (intransitive)
    (puthash "སྐྱེ" '((lemma . "སྐྱེ")
                      (meaning . "to be born, to arise")
                      (present_stem . "སྐྱེ")
                      (past_stem . "སྐྱེས")
                      (future_stem . "སྐྱེ")
                      (imperative_stem . "སྐྱེས")
                      (transitivity . "Intransitive")
                      (volitionality . "Non-volitional")
                      (case_frame . "Abs")
                      (indigenous_class . "tha_mi_dad_pa")) db)
    (puthash "སྐྱེས" (gethash "སྐྱེ" db) db)

    ;; ཤི་ - to die (intransitive)
    (puthash "ཤི" '((lemma . "ཤི")
                    (meaning . "to die")
                    (present_stem . "ཤི")
                    (past_stem . "ཤི")
                    (future_stem . "ཤི")
                    (imperative_stem . "ཤི")
                    (transitivity . "Intransitive")
                    (volitionality . "Non-volitional")
                    (case_frame . "Abs")
                    (indigenous_class . "tha_mi_dad_pa")) db)

    ;; འཕོ་ - to transfer (intransitive when dying)
    (puthash "འཕོ" '((lemma . "འཕོ")
                     (meaning . "to transfer, to pass (life)")
                     (present_stem . "འཕོ")
                     (past_stem . "འཕོས")
                     (future_stem . "འཕོ")
                     (imperative_stem . "འཕོས")
                     (transitivity . "Intransitive")
                     (volitionality . "Non-volitional")
                     (case_frame . "Abs")
                     (indigenous_class . "tha_mi_dad_pa")) db)
    (puthash "འཕོས" (gethash "འཕོ" db) db)

    ;; བཙོང་ - to sell (transitive)
    (puthash "བཙོང" '((lemma . "བཙོང")
                       (meaning . "to sell")
                       (present_stem . "བཙོང")
                       (past_stem . "བཙོངས")
                       (future_stem . "བཙོང")
                       (imperative_stem . "ཚོངས")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs")
                       (indigenous_class . "tha_dad_pa")) db)
    (puthash "བཙོངས" (gethash "བཙོང" db) db)
    (puthash "ཚོང" (gethash "བཙོང" db) db)

    ;; ཉོ་ - to buy (transitive)
    (puthash "ཉོ" '((lemma . "ཉོ")
                    (meaning . "to buy")
                    (present_stem . "ཉོ")
                    (past_stem . "ཉོས")
                    (future_stem . "ཉོ")
                    (imperative_stem . "ཉོས")
                    (transitivity . "Transitive")
                    (volitionality . "Volitional")
                    (case_frame . "Erg-Abs")
                    (indigenous_class . "tha_dad_pa")) db)
    (puthash "ཉོས" (gethash "ཉོ" db) db)

    ;; ཁྲུས་ - to wash/bathe (transitive reflexive)
    (puthash "ཁྲུས" '((lemma . "ཁྲུས")
                       (meaning . "to wash, to bathe")
                       (present_stem . "ཁྲུས")
                       (past_stem . "ཁྲུས")
                       (future_stem . "ཁྲུས")
                       (imperative_stem . "ཁྲུས")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs")
                       (indigenous_class . "tha_dad_pa")) db)

    ;; གཏོང་ - to send, to give (transitive)
    (puthash "གཏོང" '((lemma . "གཏོང")
                       (meaning . "to send, to give, to release")
                       (present_stem . "གཏོང")
                       (past_stem . "བཏང")
                       (future_stem . "གཏང")
                       (imperative_stem . "ཐོངས")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs-Dat")
                       (indigenous_class . "tha_dad_pa")) db)
    (puthash "བཏང" (gethash "གཏོང" db) db)
    (puthash "གཏང" (gethash "གཏོང" db) db)
    (puthash "ཐོངས" (gethash "གཏོང" db) db)

    ;; མཛད་ - to do (hon., transitive)
    (puthash "མཛད" '((lemma . "མཛད")
                      (meaning . "to do, to make (hon.)")
                      (present_stem . "མཛད")
                      (past_stem . "མཛད")
                      (future_stem . "མཛད")
                      (imperative_stem . "མཛད")
                      (transitivity . "Transitive")
                      (volitionality . "Volitional")
                      (case_frame . "Erg-Abs")
                      (indigenous_class . "tha_dad_pa")) db)

    ;; བསྟན་ - to show, to teach (transitive)
    (puthash "བསྟན" '((lemma . "སྟོན")
                       (meaning . "to show, to teach, to demonstrate")
                       (present_stem . "སྟོན")
                       (past_stem . "བསྟན")
                       (future_stem . "བསྟན")
                       (imperative_stem . "སྟོན")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs-Dat")
                       (indigenous_class . "tha_dad_pa")) db)
    (puthash "སྟོན" (gethash "བསྟན" db) db)

    ;; བསྔགས་ - to praise (transitive)
    (puthash "བསྔགས" '((lemma . "བསྔགས")
                         (meaning . "to praise, to commend")
                         (present_stem . "བསྔགས")
                         (past_stem . "བསྔགས")
                         (future_stem . "བསྔགས")
                         (imperative_stem . "བསྔགས")
                         (transitivity . "Transitive")
                         (volitionality . "Volitional")
                         (case_frame . "Erg-Abs")
                         (indigenous_class . "tha_dad_pa")) db)

    ;; གྲོལ་ - to be liberated (intransitive)
    (puthash "གྲོལ" '((lemma . "གྲོལ")
                       (meaning . "to be liberated, to be freed")
                       (present_stem . "གྲོལ")
                       (past_stem . "གྲོལ")
                       (future_stem . "གྲོལ")
                       (imperative_stem . "གྲོལ")
                       (transitivity . "Intransitive")
                       (volitionality . "Non-volitional")
                       (case_frame . "Abs")
                       (indigenous_class . "tha_mi_dad_pa")) db)

    ;; ཞུ་ - to melt; to request (hon.)
    (puthash "ཞུ" '((lemma . "ཞུ")
                    (meaning . "to request (hon.), to melt")
                    (present_stem . "ཞུ")
                    (past_stem . "ཞུས")
                    (future_stem . "ཞུ")
                    (imperative_stem . "ཞུས")
                    (transitivity . "Transitive")
                    (volitionality . "Volitional")
                    (case_frame . "Erg-Abs-Dat")
                    (indigenous_class . "tha_dad_pa")) db)
    (puthash "ཞུས" (gethash "ཞུ" db) db)

    ;; དྲིས་/དྲི་ - to ask
    (puthash "དྲི" '((lemma . "དྲི")
                     (meaning . "to ask, to inquire")
                     (present_stem . "དྲི")
                     (past_stem . "དྲིས")
                     (future_stem . "དྲི")
                     (imperative_stem . "དྲིས")
                     (transitivity . "Transitive")
                     (volitionality . "Volitional")
                     (case_frame . "Erg-Abs-Dat")
                     (indigenous_class . "tha_dad_pa")) db)
    (puthash "དྲིས" (gethash "དྲི" db) db)

    ;; བཏགས་ - to name, to attach
    (puthash "བཏགས" '((lemma . "གདགས")
                        (meaning . "to name, to attach, to fasten")
                        (present_stem . "གདགས")
                        (past_stem . "བཏགས")
                        (future_stem . "གདག")
                        (imperative_stem . "ཐོགས")
                        (transitivity . "Transitive")
                        (volitionality . "Volitional")
                        (case_frame . "Erg-Abs")
                        (indigenous_class . "tha_dad_pa")) db)
    (puthash "གདགས" (gethash "བཏགས" db) db)

    ;; བཙས་ - to be born (of animals/infants)
    (puthash "བཙས" '((lemma . "སྐྱེ")
                      (meaning . "to be born, to give birth")
                      (present_stem . "སྐྱེ")
                      (past_stem . "བཙས")
                      (future_stem . "སྐྱེ")
                      (imperative_stem . "སྐྱེས")
                      (transitivity . "Intransitive")
                      (volitionality . "Non-volitional")
                      (case_frame . "Abs")
                      (indigenous_class . "tha_mi_dad_pa")) db)

    ;; ཉལ་ - to sleep, to lie down
    (puthash "ཉལ" '((lemma . "ཉལ")
                     (meaning . "to sleep, to lie down")
                     (present_stem . "ཉལ")
                     (past_stem . "ཉལ")
                     (future_stem . "ཉལ")
                     (imperative_stem . "ཉོལ")
                     (transitivity . "Intransitive")
                     (volitionality . "Volitional")
                     (case_frame . "Abs")
                     (indigenous_class . "tha_mi_dad_pa")) db)
    (puthash "ཉོལ" (gethash "ཉལ" db) db)

    ;; འདུག་ - to sit, to stay (existential)
    (puthash "འདུག" '((lemma . "འདུག")
                       (meaning . "to sit, to stay; there is")
                       (present_stem . "འདུག")
                       (past_stem . "འདུག")
                       (future_stem . "འདུག")
                       (imperative_stem . "འདུག")
                       (transitivity . "Intransitive")
                       (volitionality . "Volitional")
                       (case_frame . "Abs")
                       (indigenous_class . "tha_mi_dad_pa")) db)

    ;; ཡོད་ - to have, to exist
    (puthash "ཡོད" '((lemma . "ཡོད")
                     (meaning . "to have, to exist, there is")
                     (present_stem . "ཡོད")
                     (past_stem . "ཡོད")
                     (future_stem . "ཡོད")
                     (imperative_stem . "—")
                     (transitivity . "Intransitive")
                     (volitionality . "Non-volitional")
                     (case_frame . "Abs")
                     (indigenous_class . "tha_mi_dad_pa")) db)

    ;; མེད་ - to not have, to not exist
    (puthash "མེད" '((lemma . "མེད")
                     (meaning . "to not have, to not exist")
                     (present_stem . "མེད")
                     (past_stem . "མེད")
                     (future_stem . "མེད")
                     (imperative_stem . "—")
                     (transitivity . "Intransitive")
                     (volitionality . "Non-volitional")
                     (case_frame . "Abs")
                     (indigenous_class . "tha_mi_dad_pa")) db)

    ;; ཡིན་ - to be (equative)
    (puthash "ཡིན" '((lemma . "ཡིན")
                     (meaning . "to be (equative)")
                     (present_stem . "ཡིན")
                     (past_stem . "ཡིན")
                     (future_stem . "ཡིན")
                     (imperative_stem . "—")
                     (transitivity . "Copula")
                     (volitionality . "Non-volitional")
                     (case_frame . "Abs-Abs")
                     (indigenous_class . "copula")) db)

    ;; མིན་ - not to be (equative negation of ཡིན; inherently negated)
    (puthash "མིན" '((lemma . "མིན")
                     (meaning . "not to be (equative negation)")
                     (present_stem . "མིན")
                     (past_stem . "མིན")
                     (future_stem . "མིན")
                     (imperative_stem . "—")
                     (transitivity . "Copula")
                     (volitionality . "Non-volitional")
                     (case_frame . "Abs-Abs")
                     (indigenous_class . "copula")) db)

    ;; བསླབ་ - to train, to instruct
    (puthash "བསླབ" '((lemma . "སློབ")
                       (meaning . "to train, to instruct, to learn")
                       (present_stem . "སློབ")
                       (past_stem . "བསླབས")
                       (future_stem . "བསླབ")
                       (imperative_stem . "སློབས")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs")
                       (indigenous_class . "tha_dad_pa")) db)
    (puthash "སློབ" (gethash "བསླབ" db) db)
    (puthash "བསླབས" (gethash "བསླབ" db) db)

    ;; གྱུར་ - to become
    (puthash "གྱུར" '((lemma . "འགྱུར")
                       (meaning . "to become, to change into")
                       (present_stem . "འགྱུར")
                       (past_stem . "གྱུར")
                       (future_stem . "འགྱུར")
                       (imperative_stem . "གྱུར")
                       (transitivity . "Intransitive")
                       (volitionality . "Non-volitional")
                       (case_frame . "Abs")
                       (indigenous_class . "tha_mi_dad_pa")) db)
    (puthash "འགྱུར" (gethash "གྱུར" db) db)

    ;; བཙོང་ - to sell
    (puthash "བཙོང" '((lemma . "འཚོང")
                       (meaning . "to sell")
                       (present_stem . "འཚོང")
                       (past_stem . "བཙོངས")
                       (future_stem . "བཙོང")
                       (imperative_stem . "ཚོང")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs")
                       (indigenous_class . "tha_dad_pa")) db)
    (puthash "འཚོང" (gethash "བཙོང" db) db)
    (puthash "བཙོངས" (gethash "བཙོང" db) db)

    ;; སྦྱིན་ - to give
    (puthash "སྦྱིན" '((lemma . "སྦྱིན")
                       (meaning . "to give, to bestow")
                       (present_stem . "སྦྱིན")
                       (past_stem . "བྱིན")
                       (future_stem . "སྦྱིན")
                       (imperative_stem . "སྦྱིན")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs-Dat")
                       (indigenous_class . "tha_dad_pa")) db)
    (puthash "བྱིན" (gethash "སྦྱིན" db) db)

    ;; ཁྲུས་ - to wash, bathe
    (puthash "ཁྲུས" '((lemma . "ཁྲུས")
                       (meaning . "to wash, to bathe")
                       (present_stem . "ཁྲུས")
                       (past_stem . "ཁྲུས")
                       (future_stem . "ཁྲུས")
                       (imperative_stem . "ཁྲུས")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs")
                       (indigenous_class . "tha_dad_pa")) db)

    ;; གཏོང་ - to send, to release, to let go
    (puthash "གཏོང" '((lemma . "གཏོང")
                       (meaning . "to send, to release, to let go")
                       (present_stem . "གཏོང")
                       (past_stem . "བཏང")
                       (future_stem . "གཏང")
                       (imperative_stem . "ཐོངས")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs")
                       (indigenous_class . "tha_dad_pa")) db)
    (puthash "བཏང" (gethash "གཏོང" db) db)
    (puthash "གཏང" (gethash "གཏོང" db) db)
    (puthash "ཐོངས" (gethash "གཏོང" db) db)

    ;; ཉོ་ - to buy
    (puthash "ཉོ" '((lemma . "ཉོ")
                     (meaning . "to buy")
                     (present_stem . "ཉོ")
                     (past_stem . "ཉོས")
                     (future_stem . "ཉོ")
                     (imperative_stem . "ཉོས")
                     (transitivity . "Transitive")
                     (volitionality . "Volitional")
                     (case_frame . "Erg-Abs")
                     (indigenous_class . "tha_dad_pa")) db)
    (puthash "ཉོས" (gethash "ཉོ" db) db)

    ;; འདོད་ - to want, to desire
    (puthash "འདོད" '((lemma . "འདོད")
                       (meaning . "to want, to desire, to wish")
                       (present_stem . "འདོད")
                       (past_stem . "འདོད")
                       (future_stem . "འདོད")
                       (imperative_stem . "འདོད")
                       (transitivity . "Transitive")
                       (volitionality . "Volitional")
                       (case_frame . "Erg-Abs")
                       (indigenous_class . "tha_dad_pa")) db)

    ;; ============================================================================
    ;; TIGRESS STORY VERBS (added for Tibetisch III WS25-26)
    ;; ============================================================================

    ;; བཀའ་སྩལ་ - to speak (honorific, of Buddha)
    (puthash "བཀའ་སྩལ" '((lemma . "བཀའ་སྩལ")
                           (meaning . "to speak, to say (hon. of Buddha)")
                           (present_stem . "བཀའ་སྩལ")
                           (past_stem . "བཀའ་སྩལ")
                           (future_stem . "བཀའ་སྩལ")
                           (imperative_stem . "བཀའ་སྩལ")
                           (transitivity . "Transitive")
                           (volitionality . "Volitional")
                           (case_frame . "Erg-Abs")
                           (indigenous_class . "tha_dad_pa")
                           (note . "Honorific compound verb for Buddha's speech")) db)

    ;; ཟད་ - to exhaust, to finish (in མ་ཟད = not only)
    (puthash "ཟད" '((lemma . "ཟད")
                     (meaning . "to exhaust, to finish, to be completed; in མ་ཟད: not only")
                     (present_stem . "ཟད")
                     (past_stem . "ཟད")
                     (future_stem . "ཟད")
                     (imperative_stem . "ཟད")
                     (transitivity . "Intransitive")
                     (volitionality . "Non-volitional")
                     (case_frame . "Abs")
                     (indigenous_class . "tha_mi_dad_pa")) db)

    ;; གསོ་ - to nourish, to nurture
    (puthash "གསོ" '((lemma . "གསོ")
                      (meaning . "to nourish, to nurture, to sustain, to raise")
                      (present_stem . "གསོ")
                      (past_stem . "གསོས")
                      (future_stem . "གསོ")
                      (imperative_stem . "གསོས")
                      (transitivity . "Transitive")
                      (volitionality . "Volitional")
                      (case_frame . "Erg-Abs")
                      (indigenous_class . "tha_dad_pa")) db)
    (puthash "གསོས" (gethash "གསོ" db) db)

    ;; ལྡན་ - to be endowed with, to possess
    (puthash "ལྡན" '((lemma . "ལྡན")
                      (meaning . "to be endowed with, to possess, to have")
                      (present_stem . "ལྡན")
                      (past_stem . "ལྡན")
                      (future_stem . "ལྡན")
                      (imperative_stem . "ལྡན")
                      (transitivity . "Intransitive")
                      (volitionality . "Non-volitional")
                      (case_frame . "Abs-Term")
                      (indigenous_class . "tha_mi_dad_pa")
                      (note . "Takes terminative case for what one is endowed with")) db)

    ;; འདྲ་ - to be similar, to resemble
    (puthash "འདྲ" '((lemma . "འདྲ")
                      (meaning . "to be similar, to resemble, to be like")
                      (present_stem . "འདྲ")
                      (past_stem . "འདྲ")
                      (future_stem . "འདྲ")
                      (imperative_stem . "འདྲ")
                      (transitivity . "Intransitive")
                      (volitionality . "Non-volitional")
                      (case_frame . "Abs-Term")
                      (indigenous_class . "tha_mi_dad_pa")
                      (note . "Takes terminative for what something is similar to")) db)

    ;; ཕམ་ - to lose, be defeated (intransitive, non-volitional)
    ;; Invariant stem; appears in Milarepa narrative as "pham nas" = having been defeated
    (puthash "ཕམ" '((lemma . "ཕམ")
                     (meaning . "to lose, to be defeated, to suffer defeat")
                     (present_stem . "ཕམ")
                     (past_stem . "ཕམ")
                     (future_stem . "ཕམ")
                     (imperative_stem . "ཕམ")
                     (transitivity . "Intransitive")
                     (volitionality . "Non-volitional")
                     (case_frame . "Abs")
                     (indigenous_class . "tha_mi_dad_pa")) db)

    ;; འཐོན་ - to go out, emerge, depart, come forth (intransitive)
    ;; Stems vary by tradition; conservative invariant entry here.
    (puthash "འཐོན" '((lemma . "འཐོན")
                       (meaning . "to go out, to depart, to emerge, to come forth")
                       (present_stem . "འཐོན")
                       (past_stem . "ཐོན")
                       (future_stem . "འཐོན")
                       (imperative_stem . "ཐོན")
                       (transitivity . "Intransitive")
                       (volitionality . "Volitional")
                       (case_frame . "Abs-Abl")
                       (indigenous_class . "tha_mi_dad_pa")) db)
    (puthash "ཐོན" (gethash "འཐོན" db) db)

    ;; སླེབ་ - to arrive, reach (intransitive)
    (puthash "སླེབ" '((lemma . "སླེབ")
                      (meaning . "to arrive, to reach")
                      (present_stem . "སླེབ")
                      (past_stem . "སླེབས")
                      (future_stem . "སླེབ")
                      (imperative_stem . "སླེབས")
                      (transitivity . "Intransitive")
                      (volitionality . "Non-volitional")
                      (case_frame . "Abs-Term")
                      (indigenous_class . "tha_mi_dad_pa")) db)
    (puthash "སླེབས" (gethash "སླེབ" db) db)

    ;; འཛུགས་ - to plant, set up, erect, stake (transitive)
    ;; Past stem བཙུགས appears in "rgyal du btsugs te" (staked as a wager)
    (puthash "འཛུགས" '((lemma . "འཛུགས")
                        (meaning . "to plant, to set up, to erect, to stake")
                        (present_stem . "འཛུགས")
                        (past_stem . "བཙུགས")
                        (future_stem . "གཟུག")
                        (imperative_stem . "ཚུགས")
                        (transitivity . "Transitive")
                        (volitionality . "Volitional")
                        (case_frame . "Erg-Abs")
                        (indigenous_class . "tha_dad_pa")) db)
    (puthash "བཙུགས" (gethash "འཛུགས" db) db)
    (puthash "གཟུག" (gethash "འཛུགས" db) db)
    (puthash "ཚུགས" (gethash "འཛུགས" db) db)

    ;; Return the database
    db))

;; Initialize on load
(setq tibetan-verb-database (tibetan-verb-database--initialize))

;; ============================================================================
;; LOOKUP FUNCTIONS
;; ============================================================================

(defun tibetan-verb-lookup (word)
  "Look up WORD in the verb database.
Returns verb entry alist if found, nil otherwise."
  (when (and word (not (string-empty-p word)))
    (let ((clean-word (string-trim word)))
      ;; Strip trailing punctuation (shad, double shad, etc.)
      (setq clean-word (replace-regexp-in-string "[།༎༔]+$" "" clean-word))
      ;; Try direct lookup
      (or (gethash clean-word tibetan-verb-database)
          ;; Try with common suffix variations
          (gethash (replace-regexp-in-string "ས$" "" clean-word) tibetan-verb-database)))))

(defun tibetan-is-verb-p (word)
  "Return non-nil if WORD is a recognized verb."
  (not (null (tibetan-verb-lookup word))))



(provide 'tibetan-verb-classifier)
;;; tibetan-verb-classifier.el ends here
